import { HttpsClient, HttpsClientOptions } from "./HttpsClient";
import { WinstonAuthenticationError, WinstonBadRequestError } from "./WinstonAIError";
import {
    AiTextDetectionRequest,
    AiTextDetectionResponse,
    AiImageDetectionRequest,
    AiImageDetectionResponse,
    AdvancedAiImageDetectionRequest,
    AdvancedAiImageDetectionResponse,
    PlagiarismRequest,
    PlagiarismResponse,
    FactCheckRequest,
    FactCheckResponse,
    TextCompareResponse,
    TextCompareRequest,
} from "./type";

interface IClient {
    detectText(request: AiTextDetectionRequest): Promise<AiTextDetectionResponse>;
    detectImage(request: AiImageDetectionRequest): Promise<AiImageDetectionResponse>;
    detectAdvancedImage(request: AdvancedAiImageDetectionRequest): Promise<AdvancedAiImageDetectionResponse>;
    checkPlagiarism(request: PlagiarismRequest): Promise<PlagiarismResponse>;
    checkFact(request: FactCheckRequest): Promise<FactCheckResponse>;
    compareText(request: TextCompareRequest): Promise<TextCompareResponse>;
}

const WINSTON_AI_BASE_API_URL = "https://api.gowinston.ai/v2";

class WinstonAIClient implements IClient {

    /**
     * The HTTP client for the Winston AI API.
     */
    private readonly httpsClient: HttpsClient;


    /**
     * The routes for the Winston AI API.
     */
    private readonly routes = {
        AI_TEXT_DETECTION: "/ai-content-detection",
        AI_IMAGE_DETECTION: "/image-detection",
        ADVANCED_AI_IMAGE_DETECTION: "/advanced-image-detection",
        PLAGIARISM_CHECKER: "/plagiarism",
        FACT_CHECKER: "/fact-checker",
        TEXT_COMPARE: "/text-compare",
    }

    constructor(apiKey: string, options: HttpsClientOptions = {}) {
        if (!apiKey || apiKey.trim() === "" || apiKey.trim() === "undefined") {
            throw new WinstonAuthenticationError({
                status: 401,
                error: "UNAUTHORIZED",
                description: "API key is required to make requests to the Winston AI API",
            });
        }

        this.httpsClient = new HttpsClient(WINSTON_AI_BASE_API_URL, apiKey, options);
    }

    /**
     * Detect whether text was written by a human or generated by AI.
     *
     * Provide `text`, a public `file` URL, or a public `website` URL.
     * If more than one is provided, the API prefers website over file over text.
     *
     * @throws {WinstonAIError} When the request is invalid or the API returns an error.
     */
    public async detectText(params: AiTextDetectionRequest): Promise<AiTextDetectionResponse> {
        if (!params.text && !params.file && !params.website) {
            throw new WinstonBadRequestError({
                status: 400,
                error: "BAD_REQUEST",
                description: "Provide text, a file URL, or a website URL",
            });
        }

        return this.httpsClient.post<AiTextDetectionResponse>(this.routes.AI_TEXT_DETECTION, params);
    }

    public async detectImage(request: AiImageDetectionRequest): Promise<AiImageDetectionResponse> {
        if (!request.url) {
            throw new WinstonBadRequestError({
                status: 400,
                error: "BAD_REQUEST",
                description: "URL is required to detect images",
            });
        }

        return this.httpsClient.post<AiImageDetectionResponse>(this.routes.AI_IMAGE_DETECTION, request);
    }

    public async detectAdvancedImage(request: AdvancedAiImageDetectionRequest): Promise<AdvancedAiImageDetectionResponse> {
        if (!request.image_url) {
            throw new WinstonBadRequestError({
                status: 400,
                error: "BAD_REQUEST",
                description: "Image URL is required to detect advanced images",
            });
        }

        return this.httpsClient.post<AdvancedAiImageDetectionResponse>(this.routes.ADVANCED_AI_IMAGE_DETECTION, request);
    }

    public async checkPlagiarism(request: PlagiarismRequest): Promise<PlagiarismResponse> {
        if (!request.text && !request.file && !request.website) {
            throw new WinstonBadRequestError({
                status: 400,
                error: "BAD_REQUEST",
                description: "Provide text, a file URL, or a website URL",
            });
        }

        return this.httpsClient.post<PlagiarismResponse>(this.routes.PLAGIARISM_CHECKER, request);
    }

    public async checkFact(request: FactCheckRequest): Promise<FactCheckResponse> {
        if (!request.text && !request.file && !request.website) {
            throw new WinstonBadRequestError({
                status: 400,
                error: "BAD_REQUEST",
                description: "Provide text, a file URL, or a website URL",
            });
        }

        return this.httpsClient.post<FactCheckResponse>(this.routes.FACT_CHECKER, request);
    }

    public async compareText(request: TextCompareRequest): Promise<TextCompareResponse> {
        if (!request.first_text && !request.second_text) {
            throw new WinstonBadRequestError({
                status: 400,
                error: "BAD_REQUEST",
                description: "Provide first and second text",
            });
        }
        
        return this.httpsClient.post<TextCompareResponse>(this.routes.TEXT_COMPARE, request);
    }

}

export {
    WinstonAIError,
    WinstonConnectionError,
    WinstonBadRequestError,
    WinstonAuthenticationError,
    WinstonPaymentRequiredError,
    WinstonPermissionDeniedError,
    WinstonUnsupportedMediaTypeError,
    WinstonRateLimitError,
    WinstonInternalServerError,
} from "./WinstonAIError";
export type { HttpsClientOptions } from "./HttpsClient";
export { WinstonAIClient };